// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.EF;

public partial class Batch
{
    [Key]


    public int BatchId { get; set; }
   // public int BatchId { get; set; }

    [StringLength(40)]
    [Unicode(false)]
    public string BatchName { get; set; }

    [Column(TypeName = "date")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? TentativeEndDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? EndDate { get; set; }

    public double? Fees { get; set; }

    public double? FeesPaid { get; set; }

    public double? Duration { get; set; }

    public double? HoursTaken { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column(TypeName = "text")]
    public string Details { get; set; }

    [Column(TypeName = "text")]
    public string Remarks { get; set; }

    [InverseProperty("Batch")]
    public virtual ICollection<BatchDetail> BatchDetails { get; set; } = new List<BatchDetail>();

    [InverseProperty("Batch")]
    public virtual ICollection<Evaluation> Evaluations { get; set; } = new List<Evaluation>();

    [InverseProperty("Batch")]
    public virtual ICollection<FeesDetail> FeesDetails { get; set; } = new List<FeesDetail>();

    [InverseProperty("Batch")]
    public virtual ICollection<Trainee> Trainees { get; set; } = new List<Trainee>();
}