// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.EF;

public partial class FacultiesSubject
{
    [Key]
    public int FacultySubjectId { get; set; }

    public int? FacultyId { get; set; }

    public int? SubjectId { get; set; }

    [Column(TypeName = "text")]
    public string Remarks { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Discontinue { get; set; }

    [ForeignKey("FacultyId")]
    [InverseProperty("FacultiesSubjects")]
    public virtual Faculty Faculty { get; set; }

    [ForeignKey("SubjectId")]
    [InverseProperty("FacultiesSubjects")]
    public virtual Subject Subject { get; set; }
}