// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.EF;

public partial class Faculty
{
    [Key]
    public int FacultyId { get; set; }

    [StringLength(40)]
    [Unicode(false)]
    public string FacultyName { get; set; }

    [Column(TypeName = "text")]
    public string Remarks { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Discontinue { get; set; }

    [InverseProperty("Faculty")]
    public virtual ICollection<FacultiesSubject> FacultiesSubjects { get; set; } = new List<FacultiesSubject>();
}