// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.EF;

public partial class TraineeAssignment
{
    [Key]
    public int AssignmentId { get; set; }

    public int? TraineeId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Asssignment { get; set; }

    public double? Score { get; set; }

    [Column(TypeName = "text")]
    public string Remarks { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Status { get; set; }

    [ForeignKey("TraineeId")]
    [InverseProperty("TraineeAssignments")]
    public virtual Trainee Trainee { get; set; }
}