// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.EF;

public partial class TrainingManagement2Context : DbContext
{
    public TrainingManagement2Context()
    {
    }

    public TrainingManagement2Context(DbContextOptions<TrainingManagement2Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Batch> Batches { get; set; }

    public virtual DbSet<BatchDetail> BatchDetails { get; set; }

    public virtual DbSet<College> Colleges { get; set; }

    public virtual DbSet<Evaluation> Evaluations { get; set; }

    public virtual DbSet<FacultiesSubject> FacultiesSubjects { get; set; }

    public virtual DbSet<Faculty> Faculties { get; set; }

    public virtual DbSet<FeesDetail> FeesDetails { get; set; }

    public virtual DbSet<Subject> Subjects { get; set; }

    public virtual DbSet<Trainee> Trainees { get; set; }

    public virtual DbSet<TraineeAssignment> TraineeAssignments { get; set; }

    public virtual DbSet<TraineeEvaluation> TraineeEvaluations { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        /*#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263. */
        => optionsBuilder.UseSqlServer("Data Source=.\\sqlexpress;Initial Catalog=TrainingManagement2;Integrated Security=True;TrustServerCertificate=true;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Batch>(entity =>
        {
            entity.HasKey(e => e.BatchId).HasName("PK__Batches__5D55CE58FBAF0D3C");
        });

        modelBuilder.Entity<BatchDetail>(entity =>
        {
            entity.HasKey(e => e.BatchDetailId).HasName("PK__BatchDet__B851B70C716B5CEE");

            entity.HasOne(d => d.Batch).WithMany(p => p.BatchDetails).HasConstraintName("FK__BatchDeta__Batch__5165187F");
        });

        modelBuilder.Entity<College>(entity =>
        {
            entity.HasKey(e => e.CollegeId).HasName("PK__Colleges__2940953985167CB9");
        });

        modelBuilder.Entity<Evaluation>(entity =>
        {
            entity.HasKey(e => e.EvaluationId).HasName("PK__Evaluati__36AE68F3F44BA0BA");

            entity.HasOne(d => d.Batch).WithMany(p => p.Evaluations).HasConstraintName("FK__Evaluatio__Batch__52593CB8");
        });

        modelBuilder.Entity<FacultiesSubject>(entity =>
        {
            entity.HasKey(e => e.FacultySubjectId).HasName("PK__Facultie__4374186397189E9D");

            entity.Property(e => e.Discontinue).IsFixedLength();

            entity.HasOne(d => d.Faculty).WithMany(p => p.FacultiesSubjects).HasConstraintName("FK__Faculties__Facul__2B3F6F97");

            entity.HasOne(d => d.Subject).WithMany(p => p.FacultiesSubjects).HasConstraintName("FK__Faculties__Subje__5441852A");
        });

        modelBuilder.Entity<Faculty>(entity =>
        {
            entity.HasKey(e => e.FacultyId).HasName("PK__Facultie__306F630EFF9EE777");

            entity.Property(e => e.Discontinue).IsFixedLength();
        });

        modelBuilder.Entity<FeesDetail>(entity =>
        {
            entity.HasKey(e => e.FeesId).HasName("PK__FeesDeta__7BD9FD27DA430F30");

            entity.HasOne(d => d.Batch).WithMany(p => p.FeesDetails).HasConstraintName("FK__FeesDetai__Batch__5535A963");
        });

        modelBuilder.Entity<Subject>(entity =>
        {
            entity.HasKey(e => e.SubjectId).HasName("PK__Subjects__AC1BA3A81F9AF34A");
        });

        modelBuilder.Entity<Trainee>(entity =>
        {
            entity.HasKey(e => e.TraineeId).HasName("PK__Trainees__3BA911CA513560F4");

            entity.Property(e => e.Discontinue).IsFixedLength();

            entity.HasOne(d => d.Batch).WithMany(p => p.Trainees).HasConstraintName("FK__Trainees__BatchI__59063A47");

            entity.HasOne(d => d.College).WithMany(p => p.Trainees).HasConstraintName("FK__Trainees__Colleg__59FA5E80");
        });

        modelBuilder.Entity<TraineeAssignment>(entity =>
        {
            entity.HasKey(e => e.AssignmentId).HasName("PK__TraineeA__32499E778FB135A1");

            entity.HasOne(d => d.Trainee).WithMany(p => p.TraineeAssignments).HasConstraintName("FK__TraineeAs__Train__5629CD9C");
        });

        modelBuilder.Entity<TraineeEvaluation>(entity =>
        {
            entity.HasKey(e => e.TraineeEvaluationId).HasName("PK__TraineeE__32FD85A9DB30D432");

            entity.HasOne(d => d.Evaluation).WithMany(p => p.TraineeEvaluations).HasConstraintName("FK__TraineeEv__Evalu__571DF1D5");

            entity.HasOne(d => d.Trainee).WithMany(p => p.TraineeEvaluations).HasConstraintName("FK__TraineeEv__Train__5812160E");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4CB2015402");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}