// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.EF;

public partial class Trainee
{
    [Key]
    public int TraineeId { get; set; }

    public int? BatchId { get; set; }

    public int? CollegeId { get; set; }

    [StringLength(40)]
    [Unicode(false)]
    public string TraineeName { get; set; }

    [StringLength(40)]
    [Unicode(false)]
    public string TraineeLocation { get; set; }

    [StringLength(40)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string Phone { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Discontinue { get; set; }

    [ForeignKey("BatchId")]
    [InverseProperty("Trainees")]
    public virtual Batch Batch { get; set; }

    [ForeignKey("CollegeId")]
    [InverseProperty("Trainees")]
    public virtual College College { get; set; }

    [InverseProperty("Trainee")]
    public virtual ICollection<TraineeAssignment> TraineeAssignments { get; set; } = new List<TraineeAssignment>();

    [InverseProperty("Trainee")]
    public virtual ICollection<TraineeEvaluation> TraineeEvaluations { get; set; } = new List<TraineeEvaluation>();
}