// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.EF;

public partial class User
{
    [Key]
    public int UserId { get; set; }

    [Required]
    [StringLength(40)]
    [Unicode(false)]
    public string UserName { get; set; }

    [Required]
    [StringLength(40)]
    [Unicode(false)]
    public string Password { get; set; }

    [Required]
    [StringLength(40)]
    [Unicode(false)]
    public string Role { get; set; }
}